config/routes.rb
Cropyt::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users
  
  resources :photos do
    get "delete"
  end

  root 'photos#index'
  

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	belongs_to :user
	
	ASPECT_RATIOS = ['Large', 'Small']
	DEFAULT_IMAGE_WIDTH = 900	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :photos, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    after_filter :flash_to_headers

    def flash_to_headers
        return unless request.xhr?
        response.headers['X-Message'] = flash_message
        response.headers["X-Message-Type"] = flash_type.to_s
        flash.discard # don't want the flash to appear when you reload page
    end

    private

    def flash_message
        [:error, :warning, :notice].each do |type|
            return flash[type] unless flash[type].blank?
        end
    end

    def flash_type
        [:error, :warning, :notice].each do |type|
            return type unless flash[type].blank?
        end
    end
end

app/controllers/photos_controller.rb
require 'RMagick'

class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /photos
  # GET /photos.json
  def index
    @photos = current_user.photos    
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photos = current_user.photos  
    @photo = Photo.new
    if current_user.photos.count >= 5   
      flash.now[:error] = "Only a maximim of 5 photos allowed, please delete some and try again!"      
    end    
  end

  # GET /photos/1/edit
  def edit    
  end

  # POST /photos
  # POST /photos.json
  def create
    @photos = current_user.photos
    @photo = Photo.new(photo_params)    
    @photo.user = current_user    
    @photo.save
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update    
      if @photo.update(photo_params)       
        image = Magick::Image.read(@photo.image.current_path).first
        filename = File.basename(image.filename).downcase
        
        puts @photo.to_yaml

        boundX = Photo::DEFAULT_IMAGE_WIDTH
        boundY = image.rows.to_f * boundX.to_f / image.columns.to_f
        puts "boundX: #{boundX}"
        puts "boundY: #{boundY}"

        puts "-----------------------"

        xRatio = image.columns.to_f / boundX.to_f
        yRatio = image.rows.to_f / boundY.to_f
        puts "xRatio: #{xRatio}"
        puts "yRatio: #{yRatio}"

        puts "-----------------------"

        x1Relative = xRatio.to_f * @photo.x1.to_f
        y1Relative = yRatio.to_f * @photo.y1.to_f        
        puts "x1Relative: #{x1Relative}"
        puts "y1Relative: #{y1Relative}"

        puts "-----------------------"

        wRelative = xRatio.to_f * @photo.w.to_f
        hRelative = yRatio.to_f * @photo.h.to_f
        puts "wRelative: #{wRelative}"
        puts "hRelative: #{hRelative}"

        puts "-----------------------"

        image.crop!(x1Relative, y1Relative, wRelative, hRelative)                
        puts "Cropped Width: #{image.columns}"
        puts "Cropped Height: #{image.rows}"
        
        puts "-----------------------"
        
        image.resize_to_fit!(@photo.arX)
        puts "Scaled Width: #{image.columns}"
        puts "Scaled Height: #{image.rows}"

        if not @photo.overlay_text.blank?
          #ADD THE OVERLAY
          overlay = Magick::Image.new(@photo.arX, 35) {
            self.background_color = "rgba(0,0,0,0.5)"
          }

          overlayText = Magick::Draw.new
          overlayText.annotate(overlay, 0,0,0,0, @photo.overlay_text) {
              self.font_family = 'Arial'
              self.fill = 'white'            
              self.pointsize = 20
              #self.font_weight = Magick::BoldWeight
              self.gravity = Magick::CenterGravity
              self.text_align(Magick::CenterAlign)
          }

          # Combine them!
          image.composite!(overlay, Magick::SouthGravity, Magick::OverCompositeOp)
        end

        send_data image.to_blob, filename: filename, type: "image/" + image.format.downcase
        
        puts "-----------------------"
      else
        respond_to do |format|
          format.html { render action: 'edit' }
          format.json { render json: @photo.errors, status: :unprocessable_entity }
        end
      end
  end


  def delete    
    @photo = Photo.find(params[:photo_id])    
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
      @photos = current_user.photos
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:user_id, :image, :x1, :y1, :x2, :y2, :h, :w, :overlay_text, :arX, :arY, :aspectRatio, :rW, :rH)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crop.yt</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  
  <meta name="viewport" content="initial-scale = 1.0,maximum-scale = 1.0" />
  <%= csrf_meta_tags %>
  <script>var __adobewebfontsappname__ = "reflow"</script>
  <script src="http://use.edgefonts.net/engagement:n4:all;nunito:n7,n4,n3:all;pacifico:n4:all.js"></script>  
</head>
<body>

<div id="primaryContainer" class="primaryContainer clearfix">
  <div id="main">
    <nav class="navbar" style="border-radius:0px" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <a class="navbar-brand" href="#"></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->        
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %> 
            <% if controller_name == 'photos' && action_name == 'index'  %>
              <li class="active"><%= link_to 'My images', photos_path %></li>
            <% else %>
              <li><%= link_to 'My images', photos_path %></li>
            <% end %>
          <% end %>
          
          <li>
            <% if user_signed_in? %>  
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            <% else %>
              <%= link_to "Sign in", new_session_path(resource_name) %>
            <% end %>
          </li>
        </ul> 

      </div>
    </nav>        
    <%= yield %>
    <div id="footer">
      <div class="container">
        <p class="text-muted">Place sticky footer content here.</p>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/photos/_crop_overlay_tools.html.erb
<ul id="crop_overlay_tools_tab" class="nav nav-tabs nav-justified">
  <li class="active"><a href="#crop" data-toggle="tab">Crop</a></li>
  <li class=""><a href="#overlay" data-toggle="tab">Overlay</a></li>
</ul>

<div id="crop_overlay_tools_tab_content" class="tab-content">
  <div class="tab-pane fade active in" id="crop">
    <%= render 'crop_tools', f: f %>     
  </div>
  <div class="tab-pane fade" id="overlay">
    <%= render 'overlay_tools', f: f %>     
  </div>
</div>

app/views/photos/_crop_tools.html.erb
<div id="ratio-panel" class="panel panel-default ">
	<div class="panel-heading">Ratio:</div>
	<div class="panel-body">
		<span class="pull-right">
			<div id="aspect-ratio-dpn" class="btn-group">
			  <button type="button" class="btn btn-primary dropdown-toggle btn-xs" data-toggle="dropdown">
			    Presets <span class="caret"></span>
			  </button>
			  <ul class="dropdown-menu nav nav-pills nav-stacked nav-pills-xs" style="padding-left:5px;padding-right:5px;" >
			     <li><a id="aspect-ratio-1-1" >1:1</a></li>
			     <li><a id="aspect-ratio-3-2" >3:2</a></li>
			     <li><a id="aspect-ratio-4-3" >4:3</a></li>
			     <li><a id="aspect-ratio-16-9" >16:9</a></li>
			     <!--<li><button id="aspect-ratio-new" type="button" style="" class="btn btn-primary btn-block btn-xs">Add new</button></li>-->
			  </ul>		  
			</div>
			<%= f.text_field  :ratio_width, size: '3', readonly: 'readonly' %>
			<button id="swap-ar-btn" type="button" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-transfer"></span></button>
			<%= f.text_field  :ratio_height, size: '3', readonly: 'readonly' %>
			<button id="lock-ar-btn" type="button" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-lock"></span></button>
			<button id="reset-ar-btn" type="button" class="btn btn-primary btn-xs">Reset</button>
		</span>
	</div>
</div>
<div class="panel panel-default">
	<div class="panel-heading">Size:</div>
	<div class="panel-body">
	<p>Crop Width <span class="pull-right"><%= f.text_field  :width, size: '3', readonly: 'readonly' %></span></p> 
	<p>Crop Height <span class="pull-right"><%= f.text_field  :height, size: '3', readonly: 'readonly' %></span></p>
	<p>Final Width <span class="pull-right"><%= f.text_field  :final_width, size: '3', readonly: 'readonly' %></span></p> 
	<p>Final Height <span class="pull-right"><%= f.text_field  :final_height, size: '3', readonly: 'readonly' %></span></p>
	</div>
</div>
<div class="panel panel-default">
	<div class="panel-heading">Coordinates</div>
	<div class="panel-body">
		<p>X1 <span class="pull-right"><%= f.text_field  :x1, size: '3', readonly: 'readonly' %></span></p>
		<p>Y1 <span class="pull-right"><%= f.text_field  :y1, size: '3', readonly: 'readonly' %></span></p>
		<p>X2 <span class="pull-right"><%= f.text_field  :x2, size: '3', readonly: 'readonly' %></span></p>
		<p>Y2 <span class="pull-right"><%= f.text_field  :y2, size: '3', readonly: 'readonly' %></span></p>
	</div>
</div>

app/views/photos/_edit_js.html.erb
<script type="text/javascript">
  
  jQuery(function($){
      var opt = {
        //Loading the already saved data      
        initial_x1: <%= @photo.x1 ? @photo.x1 : 0 %>, //position x
        initial_y1: <%= @photo.y1 ? @photo.y1 : 0 %>, //postiion y
        initial_x2: <%= @photo.x2 ? @photo.x2 : 0 %>, //postion x1
        initial_y2: <%= @photo.y2 ? @photo.y2 : 0 %>, //postion x2
        initial_overlay_text: '<%= @photo.overlay_text %>',
        overlay_position: 0,
        overlay_height: 35,
        overlay_font: 'arial,sans-serif',
        overlay_font_size: 20,
        overlay_text_alignment: 'center',
        overlay_text_position: 'middle'
      }

      Crop(opt);
    });  
</script>

app/views/photos/_editor.html.erb
<!-- Image -->
<div id="image-container">
	<div id="targer-container">
  		<img alt="" id="target" name="target"  src="<%= @photo.image %>">
  	</div>
</div>

app/views/photos/_error.html.erb
<div class="modal-dialog" style="width: 400px;">
  <div class="modal-content" style="width: 400px;">
    <div class="modal-header modal-error">
      <h3>Error</h3>
    </div>
    <div class='modal-body'>
      <%= escape_javascript flash[:error]%>  
    </div>    
    <div class="actions modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>                 
  </div>
</div>

app/views/photos/_index.html.erb
<% @photos.each do |photo| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img alt="<%= photo.image.file.filename %>" src="<%= photo.image %>" style="width: 300px; height: 200px;">
      <div class="caption thumbnail-caption">
        <h4><%= photo.image.file.filename %></h4>
        <p>
          <small>
            <span class="text-primary"><strong>Overlay Text:</strong></span>
            <% if photo.overlay_text %>
              <span class="text-muted"><%= photo.overlay_text %></span>
            <% else %>
              <span class="text-muted">None</span>
            <% end %>
          </small>
        </p>
        <p>
          <small>
            <span class="text-primary"><strong>Ratio:</strong></span>
            <% if photo.aspect_ratio_x %>
              <span class="text-muted"><%= photo.aspect_ratio_x %> x <%= photo.aspect_ratio_y %></span>
            <% else %>
              <span class="text-muted">None</span>
            <% end %>
          </small>
        </p>
        <div class="pull-right pull-down">
          <%= link_to 'Edit', edit_photo_path(photo), class: 'thumbnail-btn btn btn-primary', role: 'button' %>
          <%= link_to "Delete", photo_delete_path(photo), remote: true, class: "thumbnail-btn btn btn-default" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/photos/_new.html.erb
<%= render "form" %>

app/views/photos/_overlay_tools.html.erb
<div id="overlay_tools">
	
	<div class="panel panel-default">
		<div class="panel-heading">Options:</div>
		<div class="panel-body">
			<div id="overlay_tools_state">
				<p>Enable: <span class="pull-right"><%= f.check_box :overlay_enabled %></span></p>
			</div>
			<div id="overlay_tools_height">				
				<p>Overlay height: <span class="pull-right"><%= f.text_field  :overlay_height, size: '3' %></span></p>
			</div>
			<div id="overlay_tools_position">
				<p>Overlay position: <span class="pull-right"><%= f.text_field  :overlay_position, size: '3' %></span></p>
			</div>			
		</div>
	</div>	

	<div class="panel panel-default">
		<div class="panel-heading">Overlay Text:</div>
		<div class="panel-body">
			<div id="overlay_tools_text">
				<%= f.text_area :overlay_text, class: "form-control" %>
			</div>
			<div id="overlay_tools_alignment">
				<div id="text_alignment_btn_group" class="btn-group ">
					<!-- <span class="pull-right"><%= f.text_field  :overlay_text_alignment, size: '3' %></span> -->
			        <button id="left_text_alignment_btn" type="button" class="btn btn-primary btn-sm">
			        	<span class="glyphicon glyphicon-align-left"></span>
			        </button>
			        <button id="center_text_alignment_btn" type="button" class="btn btn-primary btn-sm">
			        	<span class="glyphicon glyphicon-align-center"></span>
			        </button>
			        <button id="right_text_alignment_btn" type="button" class="btn btn-primary btn-sm">
			        	<span class="glyphicon glyphicon-align-right"></span>
			        </button>
			    </div>
			    <div id="text_position_btn_group" class="btn-group ">
			      <!-- <span class="pull-right"><%= f.text_field  :overlay_text_position, size: '3' %></span> -->
				  <button id="top_text_position_btn" type="button" class="btn btn-primary btn-sm">Top</button>
				  <button id="middle_text_position_btn" type="button" class="btn btn-primary btn-sm">Middle</button>
				  <button id="bottom_text_position_btn" type="button" class="btn btn-primary btn-sm">Bottom</button>
				</div>
			</div>

			<div id="overlay_tools_height">				
				<p>Font Size: <span class="pull-right"><%= f.text_field  :overlay_text_size, size: '3' %></span></p>
				<p>Font Family: <select id="google_font_selector" class="pull-right form-control bfh-googlefonts" data-filter="true" data-font="Lato"></select></p>
				<!-- <span class="pull-right"><%= f.text_field  :overlay_text_font, size: '3' %></span> -->
			</div>		
		</div>
	</div>
</div>

app/views/photos/_save.js.erb
$("ul.errors").html("")
<% if @photo.errors.any? %>
  <% @photo.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>	
  $(".photo-index").html("<%= escape_javascript(render 'index') %>")
  $("#photo-modal").modal("hide")
<% end %>

app/views/photos/_tools.html.erb
<div id="PreviewContainer" class="clearfix">
    <div id="Preview" class="clearfix">
      <div id="preview-pane">
        <div class="preview-container">
          <div id="overlay-container">
            <div class="text"></div>            
            <div class="text-overlay"></div>            
          </div>            
          <img alt="" id="target" name="target"  src="<%= @photo.image %>">      
        </div>
      </div>
    </div>
</div>
<div id="CropTextOverlayTools" class="clearfix">
  <div>
    <%= button_to "Save and Download", {remote: true, form: { "data-type" => "json" }}, id: 'DownloadButton' %>
  </div>
  <%= render 'crop_overlay_tools', f: f  %>
  
</div>

app/views/photos/create.js.erb
console.log('created');

<%= render "save" %>

app/views/photos/delete.js.erb
$("#photo-modal").html("<%= escape_javascript(render 'delete') %>")
$("#photo-modal").modal("show")

app/views/photos/destroy.js.erb
<%= render "save" %>

app/views/photos/new.html.erb
<%= render 'form' %>